name: Auto Issue PR

on:
  pull_request:
    types: [opened, closed]

jobs:
  issue_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install gh
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Create or close issue based on PR action
        run: |
          pr_action=$(jq -r ".action" "$GITHUB_EVENT_PATH")
          if [ "$pr_action" = "opened" ]; then
            issue_number=$(gh issue create --title "Esto es un ejemplo de desarrollo de GA" --body "Aqui se podria escribir que es una prueba de desarrollo " --assignee @me --json number --jq '.number')
            pr_title=$(jq -r ".pull_request.title" "$GITHUB_EVENT_PATH")
            pr_url=$(gh pr create --title "$pr_title" --body "Closes #$issue_number" --json url --jq '.url')
            echo "Pull request creado: $pr_url"
          elif [ "$pr_action" = "closed" ]; then
            pr_merged=$(jq -r ".pull_request.merged" "$GITHUB_EVENT_PATH")
            if [ "$pr_merged" = "true" ]; then
              issue_number=$(jq -r ".pull_request.body | match(\"Closes #([0-9]+)\")" "$GITHUB_EVENT_PATH" | jq -r ".captures[0].string" | cut -d '#' -f 2)
              gh issue close $issue_number
              echo "Issue cerrada: #$issue_number"
            fi
          fi
