name: Ejercicio 6 

on:
  workflow_dispatch:
permissions: write-all 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
          
  call-reusable-workflow:
    permissions: write-all 
    uses: ./.github/workflows/ejercicio6-reusable.yml
    with:
      image-to-build: nginx
      tag-app: ploopez/ngnixtest:latest
    secrets:
      dhuser: ${{ secrets.DH_USER }}
      dhpass: ${{ secrets.DH_PASS }}
