name: Calculadora

on:
  push:
    branches:
      - main
      - calculadora-ejercicio4
  pull_request:
    branches:
      - main
      - calculadora-ejercicio4

jobs:
  calcular:
    runs-on: ubuntu-latest
    steps:
      - name: Ingresar operación y operandos
        id: inputs
        run: |
          read -p "Operación (+,-,*,/): " operacion
          read -p "Primer operando: " operando1
          read -p "Segundo operando: " operando2
          echo "::set-output name=operacion::$operacion"
          echo "::set-output name=operando1::$operando1"
          echo "::set-output name=operando2::$operando2"

      - name: Ejecutar calculadora
        run: |
          operacion=${{ steps.inputs.outputs.operacion }}
          operando1=${{ steps.inputs.outputs.operando1 }}
          operando2=${{ steps.inputs.outputs.operando2 }}

          # Validación de los operandos
          if ! [[ "$operacion" =~ ^[+*/-]$ ]]; then
            echo "Error: Operación no válida."
            exit 1
          fi

          if ! [[ "$operando1" =~ ^[0-9]+$ ]]; then
            echo "Error: El primer operando no es un número válido."
            exit 1
          fi

          if ! [[ "$operando2" =~ ^[0-9]+$ ]]; then
            echo "Error: El segundo operando no es un número válido."
            exit 1
          fi

          # Realizar la operación
          case $operacion in
            "+")
              resultado=$(echo "$operando1 + $operando2" | bc)
              ;;
            "-")
              resultado=$(echo "$operando1 - $operando2" | bc)
              ;;
            "*")
              resultado=$(echo "$operando1 * $operando2" | bc)
              ;;
            "/")
              resultado=$(echo "scale=2; $operando1 / $operando2" | bc)
              ;;
          esac

          echo "Resultado: $resultado"
