name: Reusable Workflow for docker actions

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      dh_user:
        required: true
      dh_password:
        required: true
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.image }}
          tags: ${{ inputs.tag }}

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dh_user }}
          password: ${{ secrets.dh_password }}

      - name: Build container
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ inputs.tag }}

