name: On Push

on:
  push:
    branches:
      - '*'

jobs:
  show-info:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Show Runner and Branch Info
      run: |
        echo "GitHub Runner: ${{ runner.os }}"
        echo "Branch: ${{ github.ref }}"
