name: Reusable Workflow

on:
  workflow_call:
    inputs:
      image-to-build:
        required: true
        type: string
      tag-app:
        required: true
        type: string
    secrets:
      dhuser:
        required: true
      dhpass:
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.image-to-build }}
          tags: type=sha

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_PASSWORD }}

      - name: Build and Push Container
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ inputs.tag-app }}

