name: Calculadora

on:
  push:
    branches:
      - main
      - calculadora-ejercicio4
  workflow_dispatch:
    inputs:
      operacion:
        description: '+,-,*,/'
        required: true
        default: '+'
      valor1:
        description: 'Primer operando'
        required: true
      valor2:
        description: 'Segundo operando'
        required: true

jobs:
  calcular:
    runs-on: ubuntu-latest
    steps:
      - name: Ingresar operación y operandos
        if: github.event_name == 'workflow_dispatch'
        id: inputs
        run: |
          operacion=${{ github.event.inputs.operacion }}
          operando1=${{ github.event.inputs.valor1 }}
          operando2=${{ github.event.inputs.valor2 }}
          echo "::set-output name=operacion::$operacion"
          echo "::set-output name=operando1::$operando1"
          echo "::set-output name=operando2::$operando2"

      - name: Ejecutar calculadora
        run: |
          operacion=${{ github.event.inputs.operacion }}
          operando1=${{ github.event.inputs.valor1 }}
          operando2=${{ github.event.inputs.valor2 }}

          # Validación de los operandos
          if ! [[ "$operacion" =~ ^[+*/-]$ ]]; then
            echo "Error: Operación no válida."
            exit 1
          fi

          if ! [[ "$operando1" =~ ^[0-9]+$ ]]; then
            echo "Error: El primer operando no es un número válido."
            exit 1
          fi

          if ! [[ "$operando2" =~ ^[0-9]+$ ]]; then
            echo "Error: El segundo operando no es un número válido."
            exit 1
          fi

          # Realizar la operación
          case $operacion in
            "+")
              resultado=$(echo "$operando1 + $operando2" | bc)
              ;;
            "-")
              resultado=$(echo "$operando1 - $operando2" | bc)
              ;;
            "*")
              resultado=$(echo "$operando1 * $operando2" | bc)
              ;;
            "/")
              resultado=$(echo "scale=2; $operando1 / $operando2" | bc)
              ;;
          esac

          echo "Resultado: $resultado"
