name: Calculadora

on:
  push:
    branches:
      - main
      - calculadora-ejercicio4
  pull_request:
    branches:
      - main
      - calculadora-ejercicio4

jobs:
  calcular:
    runs-on: ubuntu-latest
    steps:
      - name: Ingresar operación y operandos en el orden OPERACION N1 N2
        id: inputs
        run: |
          echo "operacion=${{ github.event.inputs.operacion }}" >> $GITHUB_ENV
          echo "operando1=${{ github.event.inputs.operando1 }}" >> $GITHUB_ENV
          echo "operando2=${{ github.event.inputs.operando2 }}" >> $GITHUB_ENV

      - name: Ejecutar calculadora
        run: |
          operacion=${{ env.operacion }}
          operando1=${{ env.operando1 }}
          operando2=${{ env.operando2 }}

          # Validación de los operandos
          if ! [[ "$operando1" =~ ^[0-9]+$ ]]; then
            echo "Error: El primer operando no es un número válido."
            exit 1
          fi

          if ! [[ "$operando2" =~ ^[0-9]+$ ]]; then
            echo "Error: El segundo operando no es un número válido."
            exit 1
          fi

          # Realizar la operación
          case $operacion in
            "sumar")
              resultado=$(echo "$operando1 + $operando2" | bc)
              ;;
            "restar")
              resultado=$(echo "$operando1 - $operando2" | bc)
              ;;
            "multiplicar")
              resultado=$(echo "$operando1 * $operando2" | bc)
              ;;
            "dividir")
              resultado=$(echo "scale=2; $operando1 / $operando2" | bc)
              ;;
            *)
              echo "Error: Operación no válida."
              exit 1
              ;;
          esac

          echo "Resultado: $resultado"
