name: Calculator

on:
  workflow_dispatch:
    inputs:
      operacion:
        description: 'Operación (suma, resta, multiplicacion, division)'
        required: true
      valor_a:
        description: 'Primer valor'
        required: true
      valor_b:
        description: 'Segundo valor'
        required: true

jobs:
  calculate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Request input numbers
        id: input_numbers
        run: |
          echo "::set-output name=number_a::$(read -p 'Ingrese el primer valor: ' val_a && echo $val_a)"
          echo "::set-output name=number_b::$(read -p 'Ingrese el segundo valor: ' val_b && echo $val_b)"

      - name: Run calculator script
        run: python calculator.py ${{ github.event.inputs.operacion }} ${{ steps.input_numbers.outputs.number_a }} ${{ steps.input_numbers.outputs.number_b }}
