name: CI/CD Simulation

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build code
        run: |
          echo "Building..."
          # Aquí irían los comandos reales para compilar tu código

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run tests
        run: |
          echo "Testing..."
          # Aquí irían los comandos reales para ejecutar tus pruebas

  push:
    name: Push
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Push changes
        run: |
          echo "Pushing changes..."
          # Aquí irían los comandos reales para realizar el push
