name: ejercicio 6

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  call-reusable-docker:
    uses: ./.github/workflows/ejercicio6-reusable.yaml
    with:
      image: mysql
      tag: mysql:test
    secrets:
      dh_user: ${{ secrets.DH_USER }}
      dh_password: ${{ secrets.DH_PASSWORD }}
