name: Calculator

on:
  workflow_dispatch:
    inputs:
      operation:
        description: 'Operación a realizar (suma, resta, multiplicación, división)'
        required: true
        default: 'suma'
      value1:
        description: 'Primer valor'
        required: true
      value2:
        description: 'Segundo valor'
        required: true

jobs:
  calculate:
    runs-on: ubuntu-latest

    steps:
      - name: Check if operation is valid
        run: |
          operation="${{ github.event.inputs.operation }}"
          if [ "$operation" != "suma" ] && [ "$operation" != "resta" ] && [ "$operation" != "multiplicacion" ] && [ "$operation" != "division" ]; then
            echo "Operación inválida: $operation"
            exit 1
          fi

      - name: Perform calculation
        run: |
          operation="${{ github.event.inputs.operation }}"
          value1="${{ github.event.inputs.value1 }}"
          value2="${{ github.event.inputs.value2 }}"
          case "$operation" in
            "suma")
              result=$((value1 + value2))
              ;;
            "resta")
              result=$((value1 - value2))
              ;;
            "multiplicacion")
              result=$((value1 * value2))
              ;;
            "division")
              if [ "$value2" -eq 0 ]; then
                echo "Error: No se puede dividir por cero."
                exit 1
              fi
              result=$(awk "BEGIN {printf \"%.2f\", $value1 / $value2}")
              ;;
          esac
          echo "El resultado de $operation de $value1 y $value2 es: $result"
